POST http://localhost:5002/auth/login
Content-Type: application/json

{
"email": "p@p.dk",
"password": "123456"
}

###

GET http://localhost:5002/auth/logout

###

GET http://localhost:5002/auth/loggedin